In [2]:
print("welcome")

welcome


In [3]:
from google.colab import drive

In [4]:
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
import pandas as pd

In [7]:
df = pd.read_csv('/content/drive/MyDrive/bigdata/csv-data/spotify_global_2019_most_streamed_tracks_audio_features.csv')

In [8]:
df

Country  ...                                         Artist_img
0     global  ...  https://i.scdn.co/image/4b914c6470c8458674538a...
1     global  ...  https://i.scdn.co/image/2622edec99d68d1d141886...
2     global  ...  https://i.scdn.co/image/b1dfbe843b0b9f54ab2e58...
3     global  ...  https://i.scdn.co/image/c128f5ef4d210a67610acd...
4     global  ...  https://i.scdn.co/image/6bd59cfbd3e1e6394af710...
...      ...  ...                                                ...
1712  global  ...  https://i.scdn.co/image/652b6bb0dfaf8aa444f441...
1713  global  ...  https://i.scdn.co/image/60d0c075d6de8417a0c44d...
1714  global  ...  https://i.scdn.co/image/1d5a05673975ba0c378cd2...
1715  global  ...  https://i.scdn.co/image/984dfbcdcf7880b022478b...
1716  global  ...  https://i.scdn.co/image/f9e65e111cbb16276d2c27...

[1717 rows x 24 columns]

In [9]:
import numpy as np

In [10]:
df2 = pd.DataFrame({
                    "name": ["hong", "park"], # key(column): value(instance)
                    "age": [10, 20] # key(column): value(instance)
                    })

In [11]:
df2

name  age
0  hong   10
1  park   20

In [13]:
df2.index # return값: class

RangeIndex(start=0, stop=2, step=1)

In [14]:
df2.values # instance 값들은 array 형태

array([['hong', 10],
       ['park', 20]], dtype=object)

In [15]:
df2.name

0    hong
1    park
Name: name, dtype: object

In [17]:
df2['name']

0    hong
1    park
Name: name, dtype: object

In [18]:
df2.name.index

RangeIndex(start=0, stop=2, step=1)

In [19]:
df2.name.values

array(['hong', 'park'], dtype=object)

In [20]:
df2.name.values.tolist() # array => list : unwrapping

['hong', 'park']

data type이 중요. data type을 활용하여 data처리에 이용

In [21]:
df3 = pd.DataFrame(data = [['hong', 10], ['park', 20]], columns = ['name', 'age'])
# 리스트 형태로 데이터프레임 생성
df3

name  age
0  hong   10
1  park   20

In [22]:
df3.dtypes
# object은 string을 말함

name    object
age      int64
dtype: object

In [23]:
df3['age'].astype(float) # dtype 변경

0    10.0
1    20.0
Name: age, dtype: float64

In [24]:
df3
# CPU에서만 바꿈: 비파괴함수
# astype은 원본을 건들지 않으므로 비파괴함수
# RAM에서의 데이터는 그대로

name  age
0  hong   10
1  park   20

In [25]:
df3.dtypes

name    object
age      int64
dtype: object

In [27]:
df3['age'] = df3['age'].astype(float) # '='을 통해 RAM에 저장
# 위와 같이 변경(반영) 가능
df3

name   age
0  hong  10.0
1  park  20.0

In [28]:
df3['age'] = df3['age'].astype(int)
df3

name  age
0  hong   10
1  park   20

In [30]:
df3.dtypes

name    object
age      int64
dtype: object

In [31]:
df3.describe() # 숫자형만 통계치 보여줌

age
count   2.000000
mean   15.000000
std     7.071068
min    10.000000
25%    12.500000
50%    15.000000
75%    17.500000
max    20.000000

In [32]:
type(df3['name'])
# Series

pandas.core.series.Series

In [33]:
df3['name']
# series의 형태: index, instance

0    hong
1    park
Name: name, dtype: object

In [34]:
df3['name'].index

RangeIndex(start=0, stop=2, step=1)

In [35]:
df3['name'].values

array(['hong', 'park'], dtype=object)

In [36]:
type(df3['name'].values)

numpy.ndarray

In [38]:
# ndarray 만들기
mask2 = np.zeros((3,4)) # 입력값을 튜플 형태로 3X4 zero matrix
mask2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
arr2 = np.array([
    [1,2,3],
    [4,5,6]
], dtype=np.float64)
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
arr3 = np.array([
    [7,8,9],
    [10,11,12]
], dtype=np.float64)
arr3

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

ndarray는 연산 가능

In [41]:
arr2 + arr3

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [42]:
arr2 * arr3

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [43]:
dates = pd.date_range('20200625', periods = 6)
dates

DatetimeIndex(['2020-06-25', '2020-06-26', '2020-06-27', '2020-06-28',
               '2020-06-29', '2020-06-30'],
              dtype='datetime64[ns]', freq='D')

In [44]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=['A', 'B', 'C', 'D']) 
# 6X4 random matrix
# index는 위 날짜
# column 항목: A, B, C, D
df

A         B         C         D
2020-06-25  0.038442  1.461205  1.034503  0.641049
2020-06-26  1.968492  2.003754  1.334119  1.858441
2020-06-27 -0.251178 -0.291849 -0.577344  0.686659
2020-06-28 -0.822215  1.166133  0.365315  1.839961
2020-06-29 -0.126961 -0.576380  1.136989 -1.710728
2020-06-30 -0.951592  0.919264  0.379572  1.927836

In [45]:
type(df)

pandas.core.frame.DataFrame

In [46]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [48]:
df['A']

2020-06-25    0.038442
2020-06-26    1.968492
2020-06-27   -0.251178
2020-06-28   -0.822215
2020-06-29   -0.126961
2020-06-30   -0.951592
Freq: D, Name: A, dtype: float64

In [49]:
df.A

2020-06-25    0.038442
2020-06-26    1.968492
2020-06-27   -0.251178
2020-06-28   -0.822215
2020-06-29   -0.126961
2020-06-30   -0.951592
Freq: D, Name: A, dtype: float64

In [50]:
df[0:3] # 행

A         B         C         D
2020-06-25  0.038442  1.461205  1.034503  0.641049
2020-06-26  1.968492  2.003754  1.334119  1.858441
2020-06-27 -0.251178 -0.291849 -0.577344  0.686659

In [54]:
df[1:3] # 1번~2번 rows 추출

A         B         C         D
2020-06-26  1.968492  2.003754  1.334119  1.858441
2020-06-27 -0.251178 -0.291849 -0.577344  0.686659

In [55]:
df.loc['2020-06-25']
# index 항목값으로 인덱싱

A    0.038442
B    1.461205
C    1.034503
D    0.641049
Name: 2020-06-25 00:00:00, dtype: float64

In [57]:
df.iloc[0]
# index값을 항목순서로 인덱싱

A    0.038442
B    1.461205
C    1.034503
D    0.641049
Name: 2020-06-25 00:00:00, dtype: float64

In [58]:
df.iloc[0:2]

A         B         C         D
2020-06-25  0.038442  1.461205  1.034503  0.641049
2020-06-26  1.968492  2.003754  1.334119  1.858441

In [59]:
df.iloc[[0, 2]] # 바깥[]는 리스트가 아니라 문법, 안[]는 리스트

A         B         C         D
2020-06-25  0.038442  1.461205  1.034503  0.641049
2020-06-27 -0.251178 -0.291849 -0.577344  0.686659

In [61]:
df.iloc[1:3, 0] # [row, column]
# 하나만 쓰게 되면 row로 인식 => column을 가져오고 싶으면 row와 같이 둘 다 써야함

2020-06-26    1.968492
2020-06-27   -0.251178
Freq: D, Name: A, dtype: float64

In [62]:
df.iloc[:, 0]

2020-06-25    0.038442
2020-06-26    1.968492
2020-06-27   -0.251178
2020-06-28   -0.822215
2020-06-29   -0.126961
2020-06-30   -0.951592
Freq: D, Name: A, dtype: float64

In [63]:
df.iloc[1:3, 0:2]

A         B
2020-06-26  1.968492  2.003754
2020-06-27 -0.251178 -0.291849

In [64]:
df.loc['2020-06-25':'2020-06-27', 'A':'C']

A         B         C
2020-06-25  0.038442  1.461205  1.034503
2020-06-26  1.968492  2.003754  1.334119
2020-06-27 -0.251178 -0.291849 -0.577344

In [65]:
df.iloc[1, 2] # 행렬 기준

1.3341193158911633

In [66]:
df.iloc[1, 2] = 100 # RAM에 저장

In [67]:
df

A         B           C         D
2020-06-25  0.038442  1.461205    1.034503  0.641049
2020-06-26  1.968492  2.003754  100.000000  1.858441
2020-06-27 -0.251178 -0.291849   -0.577344  0.686659
2020-06-28 -0.822215  1.166133    0.365315  1.839961
2020-06-29 -0.126961 -0.576380    1.136989 -1.710728
2020-06-30 -0.951592  0.919264    0.379572  1.927836

In [68]:
# 행 추가
df.loc['2020-07-01'] = [100, 200, 300, 400]

In [69]:
df

A           B           C           D
2020-06-25 00:00:00    0.038442    1.461205    1.034503    0.641049
2020-06-26 00:00:00    1.968492    2.003754  100.000000    1.858441
2020-06-27 00:00:00   -0.251178   -0.291849   -0.577344    0.686659
2020-06-28 00:00:00   -0.822215    1.166133    0.365315    1.839961
2020-06-29 00:00:00   -0.126961   -0.576380    1.136989   -1.710728
2020-06-30 00:00:00   -0.951592    0.919264    0.379572    1.927836
2020-07-01           100.000000  200.000000  300.000000  400.000000

In [70]:
df.iloc[0, 0] = 100
df.iloc[2, 1] = 200
df.iloc[3, 3] = 300
df.iloc[5, 1] = 400
df

A           B           C           D
2020-06-25 00:00:00  100.000000    1.461205    1.034503    0.641049
2020-06-26 00:00:00    1.968492    2.003754  100.000000    1.858441
2020-06-27 00:00:00   -0.251178  200.000000   -0.577344    0.686659
2020-06-28 00:00:00   -0.822215    1.166133    0.365315  300.000000
2020-06-29 00:00:00   -0.126961   -0.576380    1.136989   -1.710728
2020-06-30 00:00:00   -0.951592  400.000000    0.379572    1.927836
2020-07-01           100.000000  200.000000  300.000000  400.000000