In [1]:
from sklearn.datasets import load_iris

In [2]:
iris_data = load_iris()

In [4]:
iris_data # 꽃들에 관한 정보, 4개의 elements가 각 꽃의 정보

# 각 꽃의 정보들이 "문제 데이터" => 2차원 ndarray
# target 데이터가 "정답 데이터" => 1차원 ndarray
# 문제데이터(n X m)와 정답데이터(m X 1)를 행렬로 보면 한글 "ㅓ" 모양

# 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10')} => 정답은 setosa, versicolor, virginica 3개 중 하나
# 0: setosa, 1: versicolor, 2: virginica => "labeling" => 비연속형으로 만들기


{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [5]:
iris_data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [7]:
iris_data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
iris_data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
iris_data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [11]:
iris_data.target.shape

(150,)

In [12]:
iris_data.data.shape

(150, 4)

In [13]:
import pandas as pd
import numpy as np

In [14]:
# 데이터 프레임에 넣어라.
# 데이터, 컬럼명
df = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [15]:
df['target'] = iris_data.target
df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                  5.1               3.5  ...               0.2       0
1                  4.9               3.0  ...               0.2       0
2                  4.7               3.2  ...               0.2       0
3                  4.6               3.1  ...               0.2       0
4                  5.0               3.6  ...               0.2       0
..                 ...               ...  ...               ...     ...
145                6.7               3.0  ...               2.3       2
146                6.3               2.5  ...               1.9       2
147                6.5               3.0  ...               2.0       2
148                6.2               3.4  ...               2.3       2
149                5.9               3.0  ...               1.8       2

[150 rows x 5 columns]

In [16]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [17]:
df.columns = ['sepal length', 'sepal width', 'petal length', 'petal width', 'target']

In [18]:
df

sepal length  sepal width  petal length  petal width  target
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]

In [22]:
# 공부할 데이터와 테스트용 데이터를 분리
from sklearn.model_selection import train_test_split

In [24]:
x_data = df.loc[:, 'sepal length':'petal width'] # 문제데이터
y_data = df.loc[:, 'target'] # 정답데이터

In [25]:
# 문제 데이터는 대문자, 테스트 데이터는 소문자
X_train, X_test, y_train, y_test = train_test_split(
    
    # 5가지 parameters: 문제데이터, 정답데이터, 비율, 셔플링여부, 시드값
    
    x_data, # 문제데이터
    y_data, # 정답데이터
    test_size = 0.2, # 비율 (train:test) = 8:2
    shuffle = True, # 셔플링여부
    random_state = 20 # 시드값: 처음 랜덤한 값을 그대로 사용할 수 있는 값 (seed) => 숫자는 사실 의미 없음
)

In [26]:
X_train, X_test, y_train, y_test

(     sepal length  sepal width  petal length  petal width
 95            5.7          3.0           4.2          1.2
 88            5.6          3.0           4.1          1.3
 0             5.1          3.5           1.4          0.2
 46            5.1          3.8           1.6          0.2
 11            4.8          3.4           1.6          0.2
 ..            ...          ...           ...          ...
 22            4.6          3.6           1.0          0.2
 75            6.6          3.0           4.4          1.4
 137           6.4          3.1           5.5          1.8
 15            5.7          4.4           1.5          0.4
 99            5.7          2.8           4.1          1.3
 
 [120 rows x 4 columns],
      sepal length  sepal width  petal length  petal width
 47            4.6          3.2           1.4          0.2
 73            6.1          2.8           4.7          1.2
 74            6.4          2.9           4.3          1.3
 129           7.2          3

In [28]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [30]:
# 공부방법론을 정해서 공부를 시키자.
from sklearn.neighbors import KNeighborsClassifier

In [46]:
knn = KNeighborsClassifier(n_neighbors=5) # hyper parameter: 내가 조절할 수 있는 파라미터. 범위설정 - 홀수로 
# 이웃한 것들로 비교해서 분류
# 방법론마다 hyper parameters 다름 

In [47]:
knn.fit(X_train, y_train) # 문제와 정답으로 학습

KNeighborsClassifier()

In [48]:
# 테스트용 데이터로 점수가 얼마나 나오는지 검증해보자.
pred = knn.predict(X_test) # 모의고사
pred

array([0, 1, 1, 2, 1, 1, 2, 0, 2, 0, 2, 1, 2, 0, 0, 2, 0, 1, 2, 1, 1, 2,
       2, 0, 2, 1, 1, 0, 2, 2])

In [49]:
# 모의고사 점수가 얼마가 나왔는지 확인을 해보자. => "채점"
from sklearn.metrics import accuracy_score

In [50]:
# 정확성 검사!
jumsu = accuracy_score(y_test, pred) # parameters = (정답, 학습 이후 풀이한 답)
jumsu # accuracy

0.9666666666666667

In [53]:
# SVM 공부법

In [54]:
from sklearn.svm import SVC

In [55]:
svc = SVC(kernel='rbf')

In [56]:
svc.fit(X_train, y_train)

SVC()

In [58]:
pred2 = svc.predict(X_test)
pred2

array([0, 1, 1, 2, 1, 1, 2, 0, 2, 0, 2, 1, 2, 0, 0, 2, 0, 1, 2, 1, 1, 2,
       2, 0, 1, 1, 1, 0, 2, 2])

In [59]:
jumsu2 = accuracy_score(y_test, pred2)
jumsu2

1.0