In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [15]:
# 말뭉치 => 사전 생성
corpus = ["you know I want your love", 
          "I like you",
          "what should I do", 
          "I hate you", 
          "smile face"]

In [16]:
vector = CountVectorizer()
print(vector.fit_transform(corpus).toarray()) # 빈도수 기록 => sparse matrix
print(vector.vocabulary_) # 알파벳 순서대로 columns 순서 정렬

[[0 0 0 1 0 1 0 0 1 0 1 1]
 [0 0 0 0 1 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 1 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 1 0 0 0 0]]
{'you': 10, 'know': 3, 'want': 8, 'your': 11, 'love': 5, 'like': 4, 'what': 9, 'should': 6, 'do': 0, 'hate': 2, 'smile': 7, 'face': 1}


In [17]:
cv = CountVectorizer()

In [18]:
# 1. 사전 만들기 => fit()
# 2. 사전에 들어 있는 id로 인코딩 => transform()
# 3. 1, 2를 함께 처리하고자 하는 경우 => fir_transform()

In [19]:
cv.fit_transform(corpus) # sparse matrix(희소행렬) 만들기

<5x12 sparse matrix of type '<class 'numpy.int64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [20]:
cv.fit_transform(corpus).toarray()

array([[0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [21]:
cv.vocabulary_

{'do': 0,
 'face': 1,
 'hate': 2,
 'know': 3,
 'like': 4,
 'love': 5,
 'should': 6,
 'smile': 7,
 'want': 8,
 'what': 9,
 'you': 10,
 'your': 11}

In [33]:
tfidf = TfidfVectorizer()

In [34]:
tfidf.fit(corpus)

TfidfVectorizer()

In [35]:
tfidf = tfidf.transform(corpus)
tfidf

<5x12 sparse matrix of type '<class 'numpy.float64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [36]:
tfidf.toarray()

array([[0.        , 0.        , 0.        , 0.47412465, 0.        ,
        0.47412465, 0.        , 0.        , 0.47412465, 0.        ,
        0.3175268 , 0.47412465],
       [0.        , 0.        , 0.        , 0.        , 0.83088075,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.55645052, 0.        ],
       [0.57735027, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.57735027, 0.        , 0.        , 0.57735027,
        0.        , 0.        ],
       [0.        , 0.        , 0.83088075, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.55645052, 0.        ],
       [0.        , 0.70710678, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.70710678, 0.        , 0.        ,
        0.        , 0.        ]])

In [39]:
sentence = ["i like like like hate smile"]

In [40]:
nd2array = cv.transform(sentence).toarray()
nd2array # 하나여도 2차원

array([[0, 0, 1, 0, 3, 0, 0, 1, 0, 0, 0, 0]])

In [41]:
nd2array[0] # 꺼내려면 인덱싱 / 슬라이싱 필요

array([0, 0, 1, 0, 3, 0, 0, 1, 0, 0, 0, 0])

In [46]:
tfidf = TfidfVectorizer()
nd2array = tfidf.fit_transform(sentence).toarray()
nd2array # 하나여도 2차원

array([[0.30151134, 0.90453403, 0.30151134]])

In [47]:
cv.inverse_transform(nd2array)

[array(['do', 'face', 'hate'], dtype='<U6')]

In [49]:
tfidf.inverse_transform(nd2array)

[array(['hate', 'like', 'smile'], dtype='<U5')]

In [50]:
feature_list = cv.get_feature_names() # index없이 column 값만 추출 => "사전에 무엇이 들어있는지 확인"
feature_list

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['do',
 'face',
 'hate',
 'know',
 'like',
 'love',
 'should',
 'smile',
 'want',
 'what',
 'you',
 'your']

In [52]:
# dic <--- list
dictionary = dict()
for index, element in enumerate(feature_list):
  dictionary[index] = element
dictionary

{0: 'do',
 1: 'face',
 2: 'hate',
 3: 'know',
 4: 'like',
 5: 'love',
 6: 'should',
 7: 'smile',
 8: 'want',
 9: 'what',
 10: 'you',
 11: 'your'}

In [ ]:
## 스팸을 나타내는 사전 만들기 (10개)
## 스팸이 아닌 사전 만들기 (10개)
## 광고!! 짱 좋은 판매 홍보전략입니다.!! => 스펨입니다.!!

In [ ]:
yesspam = ["광고", "홍보", "전략", "마케팅", ""]